#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcTesting
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sunil")]
	public partial class mvcTestingDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserRegistration(UserRegistration instance);
    partial void UpdateUserRegistration(UserRegistration instance);
    partial void DeleteUserRegistration(UserRegistration instance);
    #endregion
		
		public mvcTestingDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["sunilkumar"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public mvcTestingDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mvcTestingDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mvcTestingDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public mvcTestingDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InfoBook> InfoBooks
		{
			get
			{
				return this.GetTable<InfoBook>();
			}
		}
		
		public System.Data.Linq.Table<NewAdmin> NewAdmins
		{
			get
			{
				return this.GetTable<NewAdmin>();
			}
		}
		
		public System.Data.Linq.Table<DropDownValue> DropDownValues
		{
			get
			{
				return this.GetTable<DropDownValue>();
			}
		}
		
		public System.Data.Linq.Table<COMMENT> COMMENTs
		{
			get
			{
				return this.GetTable<COMMENT>();
			}
		}
		
		public System.Data.Linq.Table<UserRegistration> UserRegistrations
		{
			get
			{
				return this.GetTable<UserRegistration>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetFriend")]
		public ISingleResult<GetFriendResult> GetFriend()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetFriendResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ValidateAdmin")]
		public int ValidateAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adminName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminPassword", DbType="VarChar(50)")] string adminPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> adminCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adminCategory)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminName, adminPassword, adminCode, adminCategory);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertNewAdmin")]
		public int InsertNewAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adminName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adminPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminPhone", DbType="VarChar(15)")] string adminPhone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminAddress", DbType="VarChar(200)")] string adminAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminDesignation", DbType="VarChar(200)")] string adminDesignation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminCategory", DbType="VarChar(50)")] string adminCategory)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminName, adminPassword, adminPhone, adminAddress, adminDesignation, adminCategory);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetOnlineBookSearch")]
		public ISingleResult<GetOnlineBookSearchResult> GetOnlineBookSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookName", DbType="VarChar(100)")] string bookName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(50)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AuthorName", DbType="VarChar(100)")] string authorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookName, iSBN, authorName, category);
			return ((ISingleResult<GetOnlineBookSearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserForAdmin")]
		public ISingleResult<GetUserForAdminResult> GetUserForAdmin()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetUserForAdminResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.validateUserName")]
		public ISingleResult<validateUserNameResult> validateUserName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER", DbType="VarChar(50)")] string uSER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASS", DbType="VarChar(50)")] string pASS)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER, pASS);
			return ((ISingleResult<validateUserNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertNewUser")]
		public int InsertNewUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegName", DbType="VarChar(100)")] string regName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegUserName", DbType="VarChar(100)")] string regUserName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegPassword", DbType="VarChar(15)")] string regPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegConfirmPassword", DbType="VarChar(15)")] string regConfirmPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegEMail", DbType="VarChar(50)")] string regEMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegAddress", DbType="VarChar(50)")] string regAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegPhone", DbType="VarChar(12)")] string regPhone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegCompany", DbType="VarChar(100)")] string regCompany)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regName, regUserName, regPassword, regConfirmPassword, regEMail, regAddress, regPhone, regCompany);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserInAdminUpdate")]
		public ISingleResult<GetUserInAdminUpdateResult> GetUserInAdminUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegUserName", DbType="VarChar(50)")] string regUserName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regUserName);
			return ((ISingleResult<GetUserInAdminUpdateResult>)(result.ReturnValue));
		}
		
        //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDropDownListInfoBook")]
        //public ISingleResult<GetDropDownListInfoBookResult> GetDropDownListInfoBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Action", DbType="Int")] System.Nullable<int> action)
        //{
        //    IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), action);
        //    return ((ISingleResult<GetDropDownListInfoBookResult>)(result.ReturnValue));
        //}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAdminDropDown")]
		public ISingleResult<GetAdminDropDownResult> GetAdminDropDown()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAdminDropDownResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertComments")]
		public int InsertComments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComName", DbType="VarChar(50)")] string comName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComEMail", DbType="VarChar(50)")] string comEMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComLocation", DbType="VarChar(50)")] string comLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComComments", DbType="NVarChar(500)")] string comComments)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, comName, comEMail, comLocation, comComments);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LastUpdatedByAdmin")]
		public int LastUpdatedByAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminName", DbType="VarChar(50)")] string adminName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminName, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LastUpdatedDetails")]
		public ISingleResult<LastUpdatedDetailsResult> LastUpdatedDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<LastUpdatedDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateUserFromAdmin")]
		public int UpdateUserFromAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegName", DbType="VarChar(50)")] string regName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegUserName", DbType="VarChar(50)")] string regUserName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegEMail", DbType="VarChar(50)")] string regEMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegAddress", DbType="VarChar(50)")] string regAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegPhone", DbType="VarChar(50)")] string regPhone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegCompany", DbType="VarChar(50)")] string regCompany, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminName", DbType="VarChar(50)")] string adminName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regName, regUserName, regEMail, regAddress, regPhone, regCompany, adminName);
			return ((int)(result.ReturnValue));
		}
		
        //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUserDetailsInAdminPopup")]
        //public ISingleResult<GetUserDetailsInAdminPopupResult> GetUserDetailsInAdminPopup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RegUserName", DbType="VarChar(50)")] string regUserName)
        //{
        //    IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), regUserName);
        //    return ((ISingleResult<GetUserDetailsInAdminPopupResult>)(result.ReturnValue));
        //}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowAllComments")]
		public ISingleResult<ShowAllCommentsResult> ShowAllComments()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ShowAllCommentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteUserAcInAdmin")]
		public int DeleteUserAcInAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ForgotPassword")]
		public int ForgotPassword([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMail", DbType="VarChar(50)")] string eMail, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewPass", DbType="VarChar(50)")] string newPass, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string confirmPass)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, eMail, newPass, confirmPass);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckUserInAdmin")]
		public int CheckUserInAdmin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((int)(result.ReturnValue));
		}
		
        //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AllInfoBook")]
        //public ISingleResult<AllInfoBookResult> AllInfoBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookID", DbType="VarChar(50)")] string bookID)
        //{
        //    IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookID);
        //    return ((ISingleResult<AllInfoBookResult>)(result.ReturnValue));
        //}
		
        //[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AdminNameList")]
        //public ISingleResult<AdminNameListResult> AdminNameList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdminName", DbType="VarChar(50)")] string adminName)
        //{
        //    IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), adminName);
        //    return ((ISingleResult<AdminNameListResult>)(result.ReturnValue));
        //}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertSingleBook")]
		public int InsertSingleBook([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BookName", DbType="VarChar(100)")] string bookName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AuthorName", DbType="VarChar(100)")] string authorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Publisher", DbType="VarChar(100)")] string publisher, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="VarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ISBN", DbType="VarChar(50)")] string iSBN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PublishYear", DbType="Int")] System.Nullable<int> publishYear)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bookName, authorName, publisher, category, iSBN, publishYear);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InfoBook")]
	public partial class InfoBook
	{
		
		private short _BID;
		
		private string _Book_ID;
		
		private string _ISBN;
		
		private string _BookName;
		
		private string _AuthorName;
		
		private string _Publisher;
		
		private string _Category;
		
		private string _PublishYear;
		
		private bool _Available;
		
		private bool _Requested;
		
		public InfoBook()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BID", DbType="SmallInt NOT NULL")]
		public short BID
		{
			get
			{
				return this._BID;
			}
			set
			{
				if ((this._BID != value))
				{
					this._BID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID", DbType="Char(12)")]
		public string Book_ID
		{
			get
			{
				return this._Book_ID;
			}
			set
			{
				if ((this._Book_ID != value))
				{
					this._Book_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this._BookName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this._AuthorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this._Publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishYear", DbType="Char(4)")]
		public string PublishYear
		{
			get
			{
				return this._PublishYear;
			}
			set
			{
				if ((this._PublishYear != value))
				{
					this._PublishYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Bit NOT NULL")]
		public bool Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this._Available = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requested", DbType="Bit NOT NULL")]
		public bool Requested
		{
			get
			{
				return this._Requested;
			}
			set
			{
				if ((this._Requested != value))
				{
					this._Requested = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewAdmin")]
	public partial class NewAdmin
	{
		
		private string _adminName;
		
		private string _adminPassword;
		
		private int _AdminCode;
		
		private string _AdminPhone;
		
		private string _AdminAddress;
		
		private string _AdminDesignation;
		
		private string _AdminCategory;
		
		private System.DateTime _AdminDate;
		
		private System.Nullable<System.Guid> _UserID;
		
		private int _Active;
		
		public NewAdmin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminName", DbType="VarChar(50)")]
		public string adminName
		{
			get
			{
				return this._adminName;
			}
			set
			{
				if ((this._adminName != value))
				{
					this._adminName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPassword", DbType="VarChar(50)")]
		public string adminPassword
		{
			get
			{
				return this._adminPassword;
			}
			set
			{
				if ((this._adminPassword != value))
				{
					this._adminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCode", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int AdminCode
		{
			get
			{
				return this._AdminCode;
			}
			set
			{
				if ((this._AdminCode != value))
				{
					this._AdminCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPhone", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string AdminPhone
		{
			get
			{
				return this._AdminPhone;
			}
			set
			{
				if ((this._AdminPhone != value))
				{
					this._AdminPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminAddress", DbType="VarChar(200)")]
		public string AdminAddress
		{
			get
			{
				return this._AdminAddress;
			}
			set
			{
				if ((this._AdminAddress != value))
				{
					this._AdminAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminDesignation", DbType="VarChar(200)")]
		public string AdminDesignation
		{
			get
			{
				return this._AdminDesignation;
			}
			set
			{
				if ((this._AdminDesignation != value))
				{
					this._AdminDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCategory", DbType="VarChar(50)")]
		public string AdminCategory
		{
			get
			{
				return this._AdminCategory;
			}
			set
			{
				if ((this._AdminCategory != value))
				{
					this._AdminCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime AdminDate
		{
			get
			{
				return this._AdminDate;
			}
			set
			{
				if ((this._AdminDate != value))
				{
					this._AdminDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DropDownValues")]
	public partial class DropDownValue
	{
		
		private int _ID;
		
		private System.Nullable<int> _Sorting;
		
		private int _GroupId;
		
		private string _Description;
		
		private string _Values;
		
		public DropDownValue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sorting", DbType="Int")]
		public System.Nullable<int> Sorting
		{
			get
			{
				return this._Sorting;
			}
			set
			{
				if ((this._Sorting != value))
				{
					this._Sorting = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int NOT NULL")]
		public int GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this._Values = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COMMENTS")]
	public partial class COMMENT
	{
		
		private int _ID;
		
		private string _UserName;
		
		private string _ComName;
		
		private string _ComEMail;
		
		private string _ComLocation;
		
		private string _ComComments;
		
		private System.Nullable<System.TimeSpan> _time;
		
		public COMMENT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComName", DbType="VarChar(50)")]
		public string ComName
		{
			get
			{
				return this._ComName;
			}
			set
			{
				if ((this._ComName != value))
				{
					this._ComName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComEMail", DbType="VarChar(50)")]
		public string ComEMail
		{
			get
			{
				return this._ComEMail;
			}
			set
			{
				if ((this._ComEMail != value))
				{
					this._ComEMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComLocation", DbType="VarChar(50)")]
		public string ComLocation
		{
			get
			{
				return this._ComLocation;
			}
			set
			{
				if ((this._ComLocation != value))
				{
					this._ComLocation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComComments", DbType="NVarChar(500)")]
		public string ComComments
		{
			get
			{
				return this._ComComments;
			}
			set
			{
				if ((this._ComComments != value))
				{
					this._ComComments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time")]
		public System.Nullable<System.TimeSpan> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRegistration")]
	public partial class UserRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegID;
		
		private string _RegName;
		
		private string _RegUserName;
		
		private string _RegPassword;
		
		private string _RegConfirmPassword;
		
		private string _RegEMail;
		
		private string _RegAddress;
		
		private string _RegPhone;
		
		private string _RegCompany;
		
		private System.Nullable<System.DateTime> _TimeStamp;
		
		private string _AdminName;
		
		private bool _IsActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegIDChanging(int value);
    partial void OnRegIDChanged();
    partial void OnRegNameChanging(string value);
    partial void OnRegNameChanged();
    partial void OnRegUserNameChanging(string value);
    partial void OnRegUserNameChanged();
    partial void OnRegPasswordChanging(string value);
    partial void OnRegPasswordChanged();
    partial void OnRegConfirmPasswordChanging(string value);
    partial void OnRegConfirmPasswordChanged();
    partial void OnRegEMailChanging(string value);
    partial void OnRegEMailChanged();
    partial void OnRegAddressChanging(string value);
    partial void OnRegAddressChanged();
    partial void OnRegPhoneChanging(string value);
    partial void OnRegPhoneChanged();
    partial void OnRegCompanyChanging(string value);
    partial void OnRegCompanyChanged();
    partial void OnTimeStampChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeStampChanged();
    partial void OnAdminNameChanging(string value);
    partial void OnAdminNameChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    #endregion
		
		public UserRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this.OnRegIDChanging(value);
					this.SendPropertyChanging();
					this._RegID = value;
					this.SendPropertyChanged("RegID");
					this.OnRegIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegName", DbType="VarChar(100)")]
		public string RegName
		{
			get
			{
				return this._RegName;
			}
			set
			{
				if ((this._RegName != value))
				{
					this.OnRegNameChanging(value);
					this.SendPropertyChanging();
					this._RegName = value;
					this.SendPropertyChanged("RegName");
					this.OnRegNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegUserName", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RegUserName
		{
			get
			{
				return this._RegUserName;
			}
			set
			{
				if ((this._RegUserName != value))
				{
					this.OnRegUserNameChanging(value);
					this.SendPropertyChanging();
					this._RegUserName = value;
					this.SendPropertyChanged("RegUserName");
					this.OnRegUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPassword", DbType="VarChar(15)")]
		public string RegPassword
		{
			get
			{
				return this._RegPassword;
			}
			set
			{
				if ((this._RegPassword != value))
				{
					this.OnRegPasswordChanging(value);
					this.SendPropertyChanging();
					this._RegPassword = value;
					this.SendPropertyChanged("RegPassword");
					this.OnRegPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegConfirmPassword", DbType="VarChar(15)")]
		public string RegConfirmPassword
		{
			get
			{
				return this._RegConfirmPassword;
			}
			set
			{
				if ((this._RegConfirmPassword != value))
				{
					this.OnRegConfirmPasswordChanging(value);
					this.SendPropertyChanging();
					this._RegConfirmPassword = value;
					this.SendPropertyChanged("RegConfirmPassword");
					this.OnRegConfirmPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegEMail", DbType="VarChar(50)")]
		public string RegEMail
		{
			get
			{
				return this._RegEMail;
			}
			set
			{
				if ((this._RegEMail != value))
				{
					this.OnRegEMailChanging(value);
					this.SendPropertyChanging();
					this._RegEMail = value;
					this.SendPropertyChanged("RegEMail");
					this.OnRegEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegAddress", DbType="VarChar(50)")]
		public string RegAddress
		{
			get
			{
				return this._RegAddress;
			}
			set
			{
				if ((this._RegAddress != value))
				{
					this.OnRegAddressChanging(value);
					this.SendPropertyChanging();
					this._RegAddress = value;
					this.SendPropertyChanged("RegAddress");
					this.OnRegAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPhone", DbType="VarChar(12)")]
		public string RegPhone
		{
			get
			{
				return this._RegPhone;
			}
			set
			{
				if ((this._RegPhone != value))
				{
					this.OnRegPhoneChanging(value);
					this.SendPropertyChanging();
					this._RegPhone = value;
					this.SendPropertyChanged("RegPhone");
					this.OnRegPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegCompany", DbType="VarChar(100)")]
		public string RegCompany
		{
			get
			{
				return this._RegCompany;
			}
			set
			{
				if ((this._RegCompany != value))
				{
					this.OnRegCompanyChanging(value);
					this.SendPropertyChanging();
					this._RegCompany = value;
					this.SendPropertyChanged("RegCompany");
					this.OnRegCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this.OnTimeStampChanging(value);
					this.SendPropertyChanging();
					this._TimeStamp = value;
					this.SendPropertyChanged("TimeStamp");
					this.OnTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(50)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this.OnAdminNameChanging(value);
					this.SendPropertyChanging();
					this._AdminName = value;
					this.SendPropertyChanged("AdminName");
					this.OnAdminNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetFriendResult
	{
		
		private int _ID;
		
		private string _Name;
		
		private string _Company;
		
		private string _Education;
		
		private string _Address;
		
		private string _Phone;
		
		public GetFriendResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Education
		{
			get
			{
				return this._Education;
			}
			set
			{
				if ((this._Education != value))
				{
					this._Education = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
	}
	
	public partial class GetOnlineBookSearchResult
	{
		
		private string _Book_ID;
		
		private string _ISBN;
		
		private string _BookName;
		
		private string _AuthorName;
		
		private string _Publisher;
		
		private string _Category;
		
		public GetOnlineBookSearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID", DbType="Char(12)")]
		public string Book_ID
		{
			get
			{
				return this._Book_ID;
			}
			set
			{
				if ((this._Book_ID != value))
				{
					this._Book_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="Char(16) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this._BookName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this._AuthorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this._Publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
	
	public partial class GetUserForAdminResult
	{
		
		private string _ResultName;
		
		public GetUserForAdminResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ResultName
		{
			get
			{
				return this._ResultName;
			}
			set
			{
				if ((this._ResultName != value))
				{
					this._ResultName = value;
				}
			}
		}
	}
	
	public partial class validateUserNameResult
	{
		
		private System.Nullable<int> _Result;
		
		public validateUserNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="Int")]
		public System.Nullable<int> Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this._Result = value;
				}
			}
		}
	}
	
	public partial class GetUserInAdminUpdateResult
	{
		
		private string _RegName;
		
		private string _RegPassword;
		
		private string _RegAddress;
		
		private string _RegPhone;
		
		private string _RegCompany;
		
		private string _RegEMail;
		
		public GetUserInAdminUpdateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegName", DbType="VarChar(100)")]
		public string RegName
		{
			get
			{
				return this._RegName;
			}
			set
			{
				if ((this._RegName != value))
				{
					this._RegName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPassword", DbType="VarChar(15)")]
		public string RegPassword
		{
			get
			{
				return this._RegPassword;
			}
			set
			{
				if ((this._RegPassword != value))
				{
					this._RegPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegAddress", DbType="VarChar(50)")]
		public string RegAddress
		{
			get
			{
				return this._RegAddress;
			}
			set
			{
				if ((this._RegAddress != value))
				{
					this._RegAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPhone", DbType="VarChar(12)")]
		public string RegPhone
		{
			get
			{
				return this._RegPhone;
			}
			set
			{
				if ((this._RegPhone != value))
				{
					this._RegPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegCompany", DbType="VarChar(100)")]
		public string RegCompany
		{
			get
			{
				return this._RegCompany;
			}
			set
			{
				if ((this._RegCompany != value))
				{
					this._RegCompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegEMail", DbType="VarChar(50)")]
		public string RegEMail
		{
			get
			{
				return this._RegEMail;
			}
			set
			{
				if ((this._RegEMail != value))
				{
					this._RegEMail = value;
				}
			}
		}
	}
	
	public partial class GetDropDownListInfoBookResult
	{
		
		private string _Category;
		
		public GetDropDownListInfoBookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
	
	public partial class GetAdminDropDownResult
	{
		
		private string _Values;
		
		public GetAdminDropDownResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Values]", Storage="_Values", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Values
		{
			get
			{
				return this._Values;
			}
			set
			{
				if ((this._Values != value))
				{
					this._Values = value;
				}
			}
		}
	}
	
	public partial class LastUpdatedDetailsResult
	{
		
		private string _AdminName;
		
		private System.Nullable<System.DateTime> _LastUpdated;
		
		public LastUpdatedDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminName", DbType="VarChar(50)")]
		public string AdminName
		{
			get
			{
				return this._AdminName;
			}
			set
			{
				if ((this._AdminName != value))
				{
					this._AdminName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdated", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdated
		{
			get
			{
				return this._LastUpdated;
			}
			set
			{
				if ((this._LastUpdated != value))
				{
					this._LastUpdated = value;
				}
			}
		}
	}
	
	public partial class GetUserDetailsInAdminPopupResult
	{
		
		private string _RegName;
		
		private string _RegUserName;
		
		private string _RegPassword;
		
		private string _RegEMail;
		
		private string _RegAddress;
		
		private string _RegPhone;
		
		private string _RegCompany;
		
		public GetUserDetailsInAdminPopupResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegName", DbType="VarChar(100)")]
		public string RegName
		{
			get
			{
				return this._RegName;
			}
			set
			{
				if ((this._RegName != value))
				{
					this._RegName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegUserName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string RegUserName
		{
			get
			{
				return this._RegUserName;
			}
			set
			{
				if ((this._RegUserName != value))
				{
					this._RegUserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPassword", DbType="VarChar(15)")]
		public string RegPassword
		{
			get
			{
				return this._RegPassword;
			}
			set
			{
				if ((this._RegPassword != value))
				{
					this._RegPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegEMail", DbType="VarChar(50)")]
		public string RegEMail
		{
			get
			{
				return this._RegEMail;
			}
			set
			{
				if ((this._RegEMail != value))
				{
					this._RegEMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegAddress", DbType="VarChar(50)")]
		public string RegAddress
		{
			get
			{
				return this._RegAddress;
			}
			set
			{
				if ((this._RegAddress != value))
				{
					this._RegAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegPhone", DbType="VarChar(12)")]
		public string RegPhone
		{
			get
			{
				return this._RegPhone;
			}
			set
			{
				if ((this._RegPhone != value))
				{
					this._RegPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegCompany", DbType="VarChar(100)")]
		public string RegCompany
		{
			get
			{
				return this._RegCompany;
			}
			set
			{
				if ((this._RegCompany != value))
				{
					this._RegCompany = value;
				}
			}
		}
	}
	
	public partial class ShowAllCommentsResult
	{
		
		private string _ComName;
		
		private string _ComComments;
		
		private System.Nullable<System.DateTime> _time;
		
		public ShowAllCommentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComName", DbType="VarChar(50)")]
		public string ComName
		{
			get
			{
				return this._ComName;
			}
			set
			{
				if ((this._ComName != value))
				{
					this._ComName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComComments", DbType="NVarChar(500)")]
		public string ComComments
		{
			get
			{
				return this._ComComments;
			}
			set
			{
				if ((this._ComComments != value))
				{
					this._ComComments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
	}
	
	public partial class AllInfoBookResult
	{
		
		private string _Book_ID;
		
		private string _ISBN;
		
		private string _BookName;
		
		private string _AuthorName;
		
		private string _Publisher;
		
		private string _Category;
		
		private string _PublishYear;
		
		public AllInfoBookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID", DbType="VarChar(106)")]
		public string Book_ID
		{
			get
			{
				return this._Book_ID;
			}
			set
			{
				if ((this._Book_ID != value))
				{
					this._Book_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="Char(100)")]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this._ISBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(100)")]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this._BookName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorName", DbType="VarChar(100)")]
		public string AuthorName
		{
			get
			{
				return this._AuthorName;
			}
			set
			{
				if ((this._AuthorName != value))
				{
					this._AuthorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="NVarChar(100)")]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this._Publisher = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishYear", DbType="Char(10)")]
		public string PublishYear
		{
			get
			{
				return this._PublishYear;
			}
			set
			{
				if ((this._PublishYear != value))
				{
					this._PublishYear = value;
				}
			}
		}
	}
	
	public partial class AdminNameListResult
	{
		
		private string _adminName;
		
		private string _adminPassword;
		
		private int _AdminCode;
		
		private string _AdminPhone;
		
		private string _AdminCategory;
		
		private string _AdminDesignation;
		
		private string _AdminAddress;
		
		public AdminNameListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminName", DbType="VarChar(50)")]
		public string adminName
		{
			get
			{
				return this._adminName;
			}
			set
			{
				if ((this._adminName != value))
				{
					this._adminName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPassword", DbType="VarChar(50)")]
		public string adminPassword
		{
			get
			{
				return this._adminPassword;
			}
			set
			{
				if ((this._adminPassword != value))
				{
					this._adminPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCode", DbType="Int NOT NULL")]
		public int AdminCode
		{
			get
			{
				return this._AdminCode;
			}
			set
			{
				if ((this._AdminCode != value))
				{
					this._AdminCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminPhone", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string AdminPhone
		{
			get
			{
				return this._AdminPhone;
			}
			set
			{
				if ((this._AdminPhone != value))
				{
					this._AdminPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminCategory", DbType="VarChar(50)")]
		public string AdminCategory
		{
			get
			{
				return this._AdminCategory;
			}
			set
			{
				if ((this._AdminCategory != value))
				{
					this._AdminCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminDesignation", DbType="VarChar(200)")]
		public string AdminDesignation
		{
			get
			{
				return this._AdminDesignation;
			}
			set
			{
				if ((this._AdminDesignation != value))
				{
					this._AdminDesignation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminAddress", DbType="VarChar(200)")]
		public string AdminAddress
		{
			get
			{
				return this._AdminAddress;
			}
			set
			{
				if ((this._AdminAddress != value))
				{
					this._AdminAddress = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
